dist: xenial
sudo: required
language: python
cache: pip

git:
  submodules: true

python:
  - 3.8
services:
  - docker
install:
  - pip install -r requirements.txt
after_failure:
  - echo "FUNNEL LOGS ----------"
  - cat ./tests/test_tmp/conformance_test_v1.0_*/funnel_log.txt
notifications:
  email: false

jobs:
  include:
    - script:
        - make funnel
        - make ftp-server
        - make funnel-server
        - make ftp-conformance
      env:
        - n=ftp
    - script:
        - make funnel
        - make minio-server
        - make funnel-minio-server
        - make s3-conformance
      env:
        - n=s3
